[build-system]
requires= ["setuptools>=72.0"]

[tool.setuptools.packages.find]
where = ["."]
include = ["worker*", "platform*", "database*"]

[project]
name = "STIXHub"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Daan Willems", email = "daan@daan.nl"}
]
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "sqlalchemy",
    "psycopg[binary]",
    "asyncpg",
    "uvicorn",
    "pyyaml"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-env",
    "pytest-cov",
    "pytest-asyncio",
    "httpx",
    "types-PyYAML"
]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
env = [
    "ENV = test",
    "STIX_HUB_DATABASE_HOST=localhost",
    "STIX_HUB_DATABASE_PORT=5432",
    "STIX_HUB_DATABASE_NAME=app",
    "STIX_HUB_DATABASE_USER=postgres",
    "STIX_HUB_DATABASE_PASS=postgres",
    "STIX_HUB_DATABASE_USE_NULLPOOL=true",
    "STIX_HUB_DATABASE_ENGINE_ECHO=false",
    "STIX_HUB_ADMIN_API_KEY=test-admin-key",
    "STIX_HUB_PLATFORM_CONFIG=./tests/platform_config.yaml",
]
asyncio_mode = "auto"

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
strict = true
check_untyped_defs = true